### ISSUE TITLE
Using Mongoid and ActiveRecord migrations together

### ISSUE THREAD

**Issue by fbjork** [adacosta/mongoid_rails_migrations#24]
Is it possible to use Mongoid and ActiveRecord migrations in the same app? Right now ActiveRecord is taking precedence when running rake db:migrate

**Comment by adacosta** [comment]
Closing because no progress has been made and I don't have time to follow up on the latest/greatest forks with the feature.

**Comment by jeremyhaile** [comment]
@stevef did you ever create a pull request for this? We're trying to figure out the best workaround. Thanks!

**Comment by jarthod** [comment]
Nothing has been merged here, #53 is open with option
