### ISSUE TITLE
Setup basic travis

### ISSUE THREAD

**Issue by arthurnn** [adacosta/mongoid_rails_migrations#32]
Hi, Not sure how to test this project, 
`bundle exec rake test:mongoid:migrations` wont work.

Having a travis setup would be helpful so people know how to run tests.

**Comment by adacosta** [comment]
I removed the earlier 1.0.2 gem I eagerly pushed out earlier. It broke how the tests work. I've now fixed the tests and started on setting up travis, but it has turned into a time sink with questionable benefits. ```rake test:mongoid:migrations``` should now work for you from master. If you'd like to get the travis config working for a build, I'll merge it.

**Comment by adacosta** [comment]
As for running tests, the readme now includes instructions.
