### ISSUE TITLE
support rails 4.1.x

### ISSUE THREAD

**Issue by chenghung** [adacosta/mongoid_rails_migrations#33]
It would be great if support rails 4.1.x

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    mongoid_rails_migrations (~> 1.1.0) ruby depends on
      activesupport (>= 4.2.0) ruby

```
jbuilder (~> 2.0) ruby depends on
  activesupport (4.1.8)
```

**Comment by adacosta** [comment]
It wouldn't be a good use of my time to make this work for rails 4.1.x . It might be an easy change but still requires verification. If you'd like to make the fix, create a pull request and I'll verify and merge.
