### ISSUE TITLE
Mongoid rails migrations not working with rspec guard

### ISSUE THREAD

**Issue by vivektiwary** [adacosta/mongoid_rails_migrations#45]
When I am running all the test using RSpec guard and mongoid_rails_migrations, I am getting
> bundler: failed to load command: rspec (/home/vivek/.rbenv/versions/2.3.1/bin/rspec)
LoadError: cannot load such file -- active_model/naming

But when I remove the gem from my Gemfile, RSpec guard runs fine.

**Comment by rmm5t** [comment]
I just experienced the exact same issue after trying to introduce `guard` to an existing project.

**Comment by rmm5t** [comment]
I was able to workaround this issue by relying on a `bin/rspec` binstub in the project instead of letting guard run `bundle exec rspec`:

```ruby
guard :rspec, cmd: "bin/rspec" do
# ...
end
```

**Comment by mikwat** [comment]
This appears to have been fixed on `master`.

**Comment by jarthod** [comment]
Master has been released as `1.1.1`
