### ISSUE TITLE
Migrate to travis.com

### ISSUE THREAD

**Issue by jarthod** [adacosta/mongoid_rails_migrations#55]
Hey @adacosta, travis.org is going away and I can't migrate the project to travis.com as I'm not the owner of the repo. Could you please do it? (or transfer the repo to me if you prefer) Thanks!

**Comment by jarthod** [comment]
@adacosta please :bow:
On travis.org the test suite can take more than 2h for 1 commit because of queuing: https://travis-ci.org/github/adacosta/mongoid_rails_migrations/builds/750295036

**Comment by spuyet** [comment]
@adacosta any news ?

**Comment by jarthod** [comment]
I just moved this to Github Actions so we are not blocked: https://github.com/adacosta/mongoid_rails_migrations/actions
